(* Generated by: ocaml-crunch 
  Creation date: Sat, 7 May 2016 17:08:01 GMT *)


include V1.KV_RO
  with type id = unit
   and type 'a io = 'a Lwt.t
   and type page_aligned_buffer = Cstruct.t
   and type id = unit
val connect : unit -> [`Ok of t | `Error of error] io